// <auto-generated />
namespace KhaiJobs.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class competencesChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(competencesChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201806031117315_competencesChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
